# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Latchfield Technologies http://latchfield.com
name: "Prepare the Python environment"
description: "Prepares the Python environment leveraging cache where possible"

runs:
  using: "composite"
  steps:
    - name: Configure system
      id: config
      shell: bash
      run: |
        # Adjust permissions for action/cache
        if command -v sudo &> /dev/null; then
          sudo mkdir -p /root/.local/bin
          sudo find /root/ -type d -exec chmod a+rx {} \;
          sudo chmod -R a+r /root/.local/bin          
        fi

        # Ensure local binaries are on the PATH
        echo "/root/.local/bin" >> "$GITHUB_PATH"
        echo "${GITHUB_WORKSPACE}/.venv/bin" >> "$GITHUB_PATH"

        # Create report directores
        mkdir -p ./reports/tests
        mkdir -p ./reports/security
        mkdir -p ./reports/analysis

        # Lookup required uv version
        echo "uv_version=$(grep -Po 'required-version\s*=\s*"\K[^"]*' pyproject.toml)" >> $GITHUB_OUTPUT

    - name: Configure pipx cache
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 #v5.0.3
      id: pipx
      with:
        path: |
          /root/.local/bin/
          /root/.local/share/pipx/
          /root/.cache/uv/
        key: pipx-uv-${{ steps.config.outputs.uv_version }}

    - name: Install uv with pipx
      if: ${{ steps.pipx.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        pipx install -f "uv${{ steps.config.outputs.uv_version }}"

    - name: Install Python dependencies
      shell: bash
      run: |
        uv python ls
        uv --version
        uv sync --link-mode symlink --all-extras
