# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Latchfield Technologies http://latchfield.com
name: "Prepare the Python environment"
description: "Prepares the Python environment leveraging cache where possible"

runs:
  using: "composite"
  steps:
    - name: Configure system
      id: config
      shell: bash
      run: |
        # Ensure local binaries are on the PATH
        echo "${HOME}/.local/bin" >> "$GITHUB_PATH"
        echo "${HOME}/.local/share/pipx/bin/" >> "$GITHUB_PATH"

        # Create report directores        
        set -x
        mkdir -p ./reports/tests
        mkdir -p ./reports/security
        mkdir -p ./reports/analysis
        set +x

        # Lookup required uv version
        echo "uv_version=$(grep -Po 'required-version\s*=\s*"\K[^"]*' pyproject.toml)" >> $GITHUB_OUTPUT

    - name: Configure dependency cache
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 #v5.0.3
      id: dependencies
      with:
        path: |
          /home/runner/.local/share/pipx/
          /home/runner/.cache/uv/
        key: pipx-uv-${{ steps.config.outputs.uv_version }}-${{ hashFiles('uv.lock') }}

    - name: Install pipx tools
      if: ${{ steps.dependencies.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        set -x
        pipx install -f "uv${{ steps.config.outputs.uv_version }}"
        mkdir -p "${HOME}/.local/share/pipx/bin/"
        cp -d $(which uv) "${HOME}/.local/share/pipx/bin/"
        cp -d $(which uvx) "${HOME}/.local/share/pipx/bin/"

    - name: Install package dependencies
      shell: bash
      run: |
        set -x
        uv --version
        uv cache dir
        uv python ls        
        uv sync --link-mode symlink --all-extras
